apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: omega-api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-worker
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: omega-worker}
