apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-omega
spec:
  selector: {app.kubernetes.io/name: omega-api}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
