apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zomega-api
  namespace: zomega
spec:
  minAvailable: 1
  selector:
    matchLabels: {app: zomega-api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zomega-worker
  namespace: zomega
spec:
  minAvailable: 1
  selector:
    matchLabels: {app: zomega-worker}
