apiVersion: v1
kind: ServiceAccount
metadata: {name: omega, namespace: omega}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: omega-read, namespace: omega}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: omega-read, namespace: omega}
subjects: [{kind: ServiceAccount, name: omega, namespace: omega}]
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: omega-read}
